Repository Azure/azure-api-management-devops-resource-kit, pull requests merged in 2022-04, with the labels that each got.

#675 Add null checks on overriding config
  src/ArmTemplates/Extractor/EntityExtractors/LoggerExtractor.cs
  src/ArmTemplates/Extractor/Models/ExtractorParameters.cs
  tests/ArmTemplates.Tests/Extractor/Configuration/ExtractorConfigurationOverrideTests.cs
Labels: bug

#677 parameters-template & master-template refactoring
  src/ArmTemplates/Commands/Applications/ExtractApplicationCommand.cs
  src/ArmTemplates/Commands/Executors/ExtractorExecutor.cs
  src/ArmTemplates/Common/Constants/GlobalConstants.cs
  src/ArmTemplates/Common/Constants/ResourceTypeConstants.cs
  src/ArmTemplates/Common/FileHandlers/FileNameGenerator.cs
  src/ArmTemplates/Common/TemplateModels/MasterTemplateResource.cs
  src/ArmTemplates/Common/Templates/Abstractions/TemplateObjectParameterProperties.cs
  src/ArmTemplates/Common/Templates/Abstractions/TemplateParameterMetadata.cs
  src/ArmTemplates/Common/Templates/Abstractions/TemplateParameterProperties.cs
  src/ArmTemplates/Common/Templates/Builders/TemplateBuilder.cs
  src/ArmTemplates/Common/Templates/Master/MasterTemplateLink.cs
  src/ArmTemplates/Common/Templates/Master/MasterTemplateProperties.cs
  src/ArmTemplates/Common/Templates/Master/MasterTemplateResource.cs
  src/ArmTemplates/Common/Templates/Master/MasterTemplateResources.cs
  src/ArmTemplates/Common/Templates/NamedValues/NamedValueTemplateResource.cs
  src/ArmTemplates/Creator/TemplateCreators/APITemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/APIVersionSetTemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/AuthorizationServerTemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/BackendTemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/LoggerTemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/MasterTemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/PolicyTemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/ProductAPITemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/ProductTemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/PropertyTemplateCreator.cs
  src/ArmTemplates/Creator/TemplateCreators/TagTemplateCreator.cs
  src/ArmTemplates/Extractor/EntityExtractors/APIExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/Abstractions/EntityExtractorBase.cs
  src/ArmTemplates/Extractor/EntityExtractors/Abstractions/IApiExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/Abstractions/IMasterTemplateExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/Abstractions/IParametersExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/BackendExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/LoggerExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/MasterTemplateExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/NamedValuesExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/ParametersExtractor.cs
  src/ArmTemplates/Extractor/EntityExtractors/TagExtractor.cs
  src/ArmTemplates/ServiceExtensions.cs
  tests/ArmTemplates.Tests/Creator/TemplateCreatorTests/MasterTemplateCreatorTests.cs
  tests/ArmTemplates.Tests/Extractor/Scenarios/MasterTemplateExtractorTests.cs
Labels: refactoring

#693 upgrade to net6.0
  .azure-pipelines/main.yml
  .dockerignore
  src/ArmTemplates/ArmTemplates.csproj
  src/ArmTemplates/Dockerfile
  src/ArmTemplates/Extractor/Utilities/Executable.cs
  src/ArmTemplates/Properties/launchSettings.json
  src/Dockerfile
  src/README.md
  tests/ArmTemplates.Tests/ArmTemplates.Tests.csproj
Labels: feature

#694 Add docs on supported resources by extractor
  README.md
  docs/SupportedResources/2021-08-01.md
  docs/SupportedResources/README.md
Labels: documentation
